package pl.edu.utp;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class ConnectDatabase {
	
	public static void main(String[] args) {
		   
		   
	      try( 
	    	  //Connection connection = DataSourceHikariCP.getConnection();
	    	  Connection connection = DriverManager.getConnection("jdbc:hsqldb:file:base/test;ifexists=true;shutdown=true", "admin", "admin");
	          Statement stmt = connection.createStatement();) {

	    	 String query = "CREATE TABLE IF NOT EXISTS SAMOCHODY(" 
	    			 	+ " samochod_id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1)," 
	    			 	+ " marka VARCHAR(50) NOT NULL,"
	    			 	+ " model VARCHAR(50),"
	    			 	+ " cena INTEGER,"
	    			 	+ " typ_nadwozia VARCHAR(50),"
	    			 	+ " kolor VARCHAR(50),"
	    			 	+ " data_czas_utworzenia TIMESTAMP DEFAULT now()," 
	    			 	+ " CONSTRAINT samochod_pk PRIMARY KEY (samochod_id)"
	    			 	+ " );" ;

	    	 stmt.executeUpdate(query);
	    	 
	    	 query = "INSERT INTO SAMOCHODY(marka, model, cena, typ_nadwozia, kolor, data_czas_utworzenia)"
	    	 		+ " VALUES ('Mazda', '6', '70000', 'Sedan', 'czarny', now())";
	    	 int alteredRow = stmt.executeUpdate(query);
	    	 System.out.println("INSERT alteredRow: " + alteredRow);
	    
	    	 query = "SELECT * FROM SAMOCHODY";
	    	 ResultSet rs = stmt.executeQuery(query);
	    	 while(rs.next()) {
	    		 System.out.println("ID: " + rs.getInt("samochod_id") + ", marka pojazdu: " + rs.getString("marka"));
	    	 }

	      }  catch (SQLException e) {
	         e.printStackTrace();
	      }
	   }

}
